namespace PainTrax.Web.ViewModel
{
    public class AIIntakeFormModel
    {
        /* public string Id { get; set; }
         public string FN { get; set; }
         public string LN { get; set; }
         public string Gender { get; set; }
         public string DominantHand { get; set; }
         public string DOB { get; set; }
         public string DOA { get; set; }
         public string DOE { get; set; }
         public int Age { get; set; }
         public string Height { get; set; }
         public string Weight { get; set; }
         public string IsWorking { get; set; }
         public string JobTitle { get; set; }
         public string StoppedAfterAccident { get; set; }
         public string NotWorkingReason { get; set; }
         public List<string> Complaints { get; set; }
         public string InjuryType { get; set; }
         public string Activity { get; set; }
         public string Incident { get; set; }
         public string IncidentType { get; set; }
         public string Mechanism { get; set; }
         public string SymptomOnset { get; set; }
         public string BodyPart { get; set; }
         public string SymptomPattern { get; set; }
         public string DailyActivities { get; set; }*/

        public string Id { get; set; }
        public string FN { get; set; }
        public string LN { get; set; }
        public string Age { get; set; }
        public string LocationId { get; set; }
        public string DOA { get; set; }
        public string DOB { get; set; }
        public string DOE { get; set; }
        public string EMS { get; set; }
        public List<string> PMH { get; set; }
        public string PPD { get; set; }
        public string PSH { get; set; }
        public string Sit { get; set; }
        public string Meds { get; set; }
        public string Walk { get; set; }
        public string HdId { get; set; }
        public string Chiro { get; set; }
        public string Smoke { get; set; }
        public string Stand { get; set; }
        public string Airbag { get; set; }
        public string Gender { get; set; }
        public string Height { get; set; }
        public string PTFreq { get; set; }
        public string Police { get; set; }
        public string SitMin { get; set; }
        public List<string> Unable { get; set; }
        public string Weight { get; set; }
        public string LblDOA { get; set; }
        public string Alcohol { get; set; }
        public string Allergy { get; set; }
        public string LKnPain { get; set; }
        public List<string> LKnType { get; set; }
        public string LShPain { get; set; }
        public List<string> LShType { get; set; }
        public string RKnPain { get; set; }
        public List<string> RKnType { get; set; }
        public List<string> RShInsp { get; set; }
        public string RShPain { get; set; }
        public List<string> RShPalp { get; set; }
        public string RShProm { get; set; }
        public List<string> RShType { get; set; }
        public string Records { get; set; }
        public string Activity { get; set; }
        public string BodyPart { get; set; }
        public string Cannabis { get; set; }
        public string Hospital { get; set; }
        public string Incident { get; set; }
        public string JobTitle { get; set; }
        public string PMHOther { get; set; }
        public string PTRelief { get; set; }
        public List<string> RShNeuro { get; set; }
        public List<string> RShTests { get; set; }
        public string StandMin { get; set; }
        public string ChiroFreq { get; set; }
        public string IsWorking { get; set; }
        public string Mechanism { get; set; }
        public string MedsOther { get; set; }
        public string PreInjury { get; set; }
        public List<string> Transport { get; set; }
        public List<string> Complaints { get; set; }
        public string Compliance { get; set; }
        public string InjuryType { get; set; }
        public List<string> LKnImprove { get; set; }
        public List<string> LShImprove { get; set; }
        public string OtherDrugs { get; set; }
        public string PTDuration { get; set; }
        public string PainEffect { get; set; }
        public List<string> RKnImprove { get; set; }
        public string RShAbdPain { get; set; }
        public string RShExtPain { get; set; }
        public List<string> RShImprove { get; set; }
        public string RshFlexion { get; set; }
        public List<string> VehicleHit { get; set; }
        public string WalkBlocks { get; set; }
        public string AllergyDrug { get; set; }
        public string ChiroRelief { get; set; }
        public List<string> LKnSymptoms { get; set; }
        public List<string> LShSymptoms { get; set; }
        public List<string> PatientType { get; set; }
        public List<string> RKnSymptoms { get; set; }
        public string RShExternal { get; set; }
        public string RShFlexPain { get; set; }
        public string RShInternal { get; set; }
        public List<string> RShRomLimit { get; set; }
        public List<string> RShStrength { get; set; }
        public List<string> RShSymptoms { get; set; }
        public string AccidentType { get; set; }
        public string DominantHand { get; set; }
        public string HospitalName { get; set; }
        public string IncidentType { get; set; }
        public string PatientFName { get; set; }
        public string PatientLName { get; set; }
        public string PoliceReport { get; set; }
        public string RShAbduction { get; set; }
        public string SymptomOnset { get; set; }
        public string ChiroDuration { get; set; }
        public string LShSleepIssue { get; set; }
        public string OtherDrugsTxt { get; set; }
        public string RShSleepIssue { get; set; }
        public string SymptomsStart { get; set; }
        public bool TreatmentPlan { get; set; }
        public string SymptomPattern { get; set; }
        public string AllergyReaction { get; set; }
        public string DailyActivities { get; set; }
        public string MechanismChoice { get; set; }
        public string LShReachOverhead { get; set; }
        public string NotWorkingReason { get; set; }
        public string PreInjuryDetails { get; set; }
        public string RShReachOverhead { get; set; }
        public string SymptomsProgress { get; set; }
        public string DiscontinueReason { get; set; }
        public string MechanismInvolving { get; set; }
        public string MechanismResulting { get; set; }
        public string AccidentDescription { get; set; }
        public string StoppedAfterAccident { get; set; }
        public string __RequestVerificationToken { get; set; }
        public string PatientSubmitDate { get; set; }
        public string DLPath { get; set; }
        public string Diagnosis { get; set; }
        public string TreatmentIds { get; set; }
        public string TreatmentDesc { get; set; }
        public string TreatmentDelimitDesc { get; set; }
    }
}

